name: C++ Build Check

on:
  push:
    
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-10 cmake
        sudo apt-get install -y libboost-system-dev libboost-thread-dev libboost-serialization-dev libpqxx-dev postgresql cmake
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
    
    - name: Проверяем, что C++20 поддерживается
      run: |
        g++ --version
        echo '#include <concepts>' > test.cpp
        echo 'int main() { return 0; }' >> test.cpp
        g++ -std=c++20 test.cpp -o test && ./test
        echo "✅ C++20 поддерживается!"
    
    - name: Делаем скрипт исполняемым
      run: |
        chmod +x scripts/create_client.sh
        chmod +x scripts/create_server.sh
    
    - name: Запуск скрипта, который собирает клиента
      run: ./scripts/create_client.sh
    
    - name: Запуск скрипта, который собирает сервер
      run: ./scripts/create_server.sh
    
      
    - name: Проверяем, что сборка прошла успешно
      run: |
        if [[ -x build-client/SwiftMessage_Client && -x build-server/SwiftMessage_Server ]]; then
          echo "✅ Всё чики-пуки!"
        else
          echo "❌ Что-то пошло не так("
          exit 1
        fi
    
    - name: Запуск интеграционного теста
      run: |
        cd integration_tests
        mkdir -p build && cd build
        cmake ..
        make
        ./SwiftMessage_Tests
