name: C++ Build Check

on:
  push:
    branches: [ main, master, new_server ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y libboost-all-dev
    
    - name: Make script executable
      run: chmod +x scripts/run.sh
    
    - name: Build using run.sh script
      run: ./scripts/run.sh
    
    - name: Check build artifacts
      working-directory: build
      run: |
        if [ -f "SwiftMessage_Server" ] && [ -f "SwiftMessage_Client" ]; then
          echo "✅ Build successful!"
        else
          echo "❌ Build failed: executables not found"
          exit 1
        fi 